# Generate docker-compose.nix with `compose2nix --env_files=.env --include_env_files=true`
name: atm9
services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    user: 1000:1000
    environment:
      EULA: "true"
      MODPACK_PLATFORM: AUTO_CURSEFORGE
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-9
      # Optional: select a specific version/file
      CF_FILENAME_MATCHER: "1.0.7"
      MEMORY: 8G
      DIFFICULTY: normal
      TZ: America/Chicago
    volumes:
      - mc-data:/data
      - /mnt/k8s-nfs/backups/minecraft/atm9:/data/backups
    labels:
      - "compose2nix.settings.autoStart=false"

volumes:
  mc-data: {}
