name: atm9
services:
  mc:
    image: itzg/minecraft-server:latest
    ports:
      - 25565:25565
    environment:
      - EULA=TRUE
      - TYPE=FORGE
      - VERSION=1.20.1
      - FORGE_INSTALLER=forge-1.20.1-47.3.7-installer.jar
      - OVERRIDE_SERVER_PROPERTIES=TRUE
      - TZ=America/Chicago
      - MEMORY=8G
      - DIFFICULTY=normal
        # tty: true
        #stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data
      # - /mnt/k8s-nfs/backups/minecraft/atm9:/data/backups
    labels:
      - "compose2nix.settings.autoStart=false"
