system: "base16"
name: "Tokyonight-Night"
author: "github:folke"
variant: "dark"
palette:
  base00: "1a1b26"
  base01: "2e3440"
  base02: "414868"
  base03: "565f89"
  base04: "a9b1d6"
  base05: "c0caf5"
  base06: "d7dae0"
  base07: "f0f4fc"
  base08: "f7768e"
  base09: "ff9e64"
  base0A: "e0af68"
  base0B: "9ece6a"
  base0C: "7dcfff"
  base0D: "7aa2f7"
  base0E: "bb9af7"
  base0F: "cfc9c2"
