name: home-assistant
services:
  homeassistant:
    container_name: home-assistant
    image: "ghcr.io/home-operations/home-assistant:2025.3.4"
    user: 1000:100
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome:2025.2.0
    volumes:
      - esphome-config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    environment:
      ESPHOME_DASHBOARD_USE_PING: true
    privileged: true
    network_mode: host
  node-red:
    container_name: node-red
    image: nodered/node-red:4.0.9
    user: 1000:100
    volumes:
      - node-red-config:/data
    restart: unless-stopped
    ports:
      - 1880:1880
    environment:
      TZ: America/Chicago

volumes:
  esphome-config:
  node-red-config:
