# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };

  # Enable container name DNS for non-default Podman networks.
  # https://github.com/NixOS/nixpkgs/issues/226365
  networking.firewall.interfaces."podman+".allowedUDPPorts = [ 53 ];

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."syncthing" = {
    image = "syncthing/syncthing:1.28";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
    };
    volumes = [
      "/mnt/k8s-nfs:/data:rw"
      "syncthing_syncthing-config:/var/syncthing:rw"
    ];
    ports = [
      "8384:8384/tcp"
      "22000:22000/tcp"
      "22000:22000/udp"
      "21027:21027/udp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1"
      "--health-interval=1m0s"
      "--health-retries=3"
      "--health-timeout=10s"
      "--hostname=my-syncthing"
      "--network-alias=syncthing"
      "--network=syncthing_default"
    ];
  };
  systemd.services."podman-syncthing" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-syncthing_default.service"
      "podman-volume-syncthing_syncthing-config.service"
    ];
    requires = [
      "podman-network-syncthing_default.service"
      "podman-volume-syncthing_syncthing-config.service"
    ];
    partOf = [
      "podman-compose-syncthing-root.target"
    ];
    wantedBy = [
      "podman-compose-syncthing-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-syncthing_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f syncthing_default";
    };
    script = ''
      podman network inspect syncthing_default || podman network create syncthing_default
    '';
    partOf = [ "podman-compose-syncthing-root.target" ];
    wantedBy = [ "podman-compose-syncthing-root.target" ];
  };

  # Volumes
  systemd.services."podman-volume-syncthing_syncthing-config" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect syncthing_syncthing-config || podman volume create syncthing_syncthing-config
    '';
    partOf = [ "podman-compose-syncthing-root.target" ];
    wantedBy = [ "podman-compose-syncthing-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-syncthing-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
